# Site Build Settings

# Set comment
livere: true
livere_uid: "MTAyMC80MDEwOS8xNjYzNg=="

# jekyll-paginate configuration
paginate:            3

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Dream of DaoDreamer"
description:	       "Welcome to my dream."
author:              "DaoDreamer"
url:      "https://blog.daodreamer.com"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml

# Baidu analysis
baidu: true
baidu-url: "202265785f84bbb39ba050c572b7567f"

# Google Analysis
google: ture
google-ID: "UA-127071261-1"