# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'DaoDreamer'

google-ID: 'UA-112060364-2'

menu:
- {name: 'Interesting Facts', folder: 'pages', file: 'facts.html'}
- {name: 'Learning Resources', folder: 'pages', file: 'resources.html'}
- {name: 'Documentation', folder: 'pages', file: 'documentation.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'weibo', link: 'https://weibo.com/1604955832/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1'}
- {icon: 'qq', link: 'https://wpa.qq.com/msgrd?v=3&uin=550247000&site=qq&menu=yes'}
- {icon: 'envelope', link: 'mailto:550247000@qq.com'}
- {icon: 'github', link: 'https://github.com/daodreamer'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'If you like my article, you could share this article or my blog to your friends!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
